In [1]:
import pandas as pandas
import pathlib, os

In [2]:
dataset_dir = os.path.join(os.path.abspath("../"), "data","raw","trec-covid")
corpus_dir = os.path.join(dataset_dir,"corpus.jsonl")
queries_dir = os.path.join(dataset_dir,"queries.jsonl")
qrels_dir = os.path.join(dataset_dir,"qrels","test.tsv")

In [3]:
corpus = pandas.read_json(corpus_dir, lines=True)
corpus.head(10)

,_id,title,text,metadata
0,ug7v899j,Clinical features of culture-proven Mycoplasma...,OBJECTIVE: This retrospective chart review des...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
1,02tnwd4m,Nitric oxide: a pro-inflammatory mediator in l...,Inflammatory diseases of the respiratory tract...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
2,ejv2xln0,Surfactant protein-D and pulmonary host defense,Surfactant protein-D (SP-D) participates in th...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
3,2b73a28n,Role of endothelin-1 in lung disease,Endothelin-1 (ET-1) is a 21 amino acid peptide...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
4,9785vg6d,Gene expression in epithelial cells in respons...,Respiratory syncytial virus (RSV) and pneumoni...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
5,zjufx4fo,Sequence requirements for RNA strand transfer ...,Nidovirus subgenomic mRNAs contain a leader se...,{'url': 'http://europepmc.org/articles/pmc1253...
6,5yhe786e,Debate: Transfusing to normal haemoglobin leve...,Recent evidence suggests that critically ill p...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
7,8zchiykl,The 21st International Symposium on Intensive ...,The 21st International Symposium on Intensive ...,{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
8,8qnrcgnk,Heme oxygenase-1 and carbon monoxide in pulmon...,"Heme oxygenase-1 (HO-1), an inducible stress p...",{'url': 'https://www.ncbi.nlm.nih.gov/pmc/arti...
9,jg13scgo,Technical Description of RODS: A Real-time Pub...,This report describes the design and implement...,{'url': 'https://academic.oup.com/jamia/articl...

In [ ]:
queries = pandas.read_json(queries_dir, lines=True)
queries.head(10)

,_id,text,metadata
0,1,what is the origin of COVID-19,"{'query': 'coronavirus origin', 'narrative': '..."
1,2,how does the coronavirus respond to changes in...,{'query': 'coronavirus response to weather cha...
2,3,will SARS-CoV2 infected people develop immunit...,"{'query': 'coronavirus immunity', 'narrative':..."
3,4,what causes death from Covid-19?,{'query': 'how do people die from the coronavi...
4,5,what drugs have been active against SARS-CoV o...,"{'query': 'animal models of COVID-19', 'narrat..."
5,6,what types of rapid testing for Covid-19 have ...,"{'query': 'coronavirus test rapid testing', 'n..."
6,7,are there serological tests that detect antibo...,"{'query': 'serological tests for coronavirus',..."
7,8,how has lack of testing availability led to un...,"{'query': 'coronavirus under reporting', 'narr..."
8,9,how has COVID-19 affected Canada,"{'query': 'coronavirus in Canada', 'narrative'..."
9,10,has social distancing had an impact on slowing...,{'query': 'coronavirus social distancing impac...

In [ ]:
qrels = pandas.read_csv(qrels_dir)
qrels.head(10)

  query-id\tcorpus-id\tscore
0             1\t005b2j4b\t2
1             1\t00fmeepz\t1
2             1\tg7dhmyyo\t2
3             1\t0194oljo\t1
4             1\t021q9884\t1
5             1\t02f0opkr\t1
6             1\t047xpt2c\t0
7             1\t04ftw7k9\t0
8             1\tpl9ht0d0\t0
9             1\t05vx82oo\t0

In [ ]:
print("Corpus size: ", corpus.shape)
print("Queries size: ", queries.shape)
print("Qrels size: ", qrels.shape)

Corpus size:  (171332, 4)
Queries size:  (50, 3)
Qrels size:  (66336, 1)

In [3]:
embeddings = (1,992)
print(embeddings.shape)  # (1, 768) ← عدد دوم dimension هست

AttributeError: 'tuple' object has no attribute 'shape'